# Generated by Django 4.1.7 on 2023-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_user_is_active_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.IntegerField()),
                ('total_spending', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('user', 'meeting_schedule')},
        ),
    ]
