# Generated by Django 4.1.7 on 2023-05-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_warning_group_warning_month_warning_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstatistic',
            name='statistic_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='statistic_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
