# Generated by Django 4.1.7 on 2023-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_groupstatistic_statistic_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spending_amount',
        ),
        migrations.AddField(
            model_name='groupstatistic',
            name='income_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupstatistic',
            name='percent',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupstatistic',
            name='spending_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='income_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstatistic',
            name='spending_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupstatistic',
            name='statistic_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatistic',
            name='statistic_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
