# Generated by Django 4.1.7 on 2023-05-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_project_income_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstatistic',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='groupstatistic',
            name='spending_amount',
        ),
        migrations.AddField(
            model_name='group',
            name='income_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='spending_amount',
            field=models.IntegerField(default=0),
        ),
    ]
