# Generated by Django 4.1.7 on 2023-05-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_groupstatistic_income_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstatistic',
            old_name='percent',
            new_name='percent_income',
        ),
        migrations.AddField(
            model_name='groupstatistic',
            name='percent_spending',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
