# Generated by Django 4.1.7 on 2023-05-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_percent_groupstatistic_percent_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstatistic',
            name='statistic_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatistic',
            name='statistic_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
