# Generated by Django 4.1.7 on 2023-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_projectstatistic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warning',
            old_name='status',
            new_name='status_income',
        ),
        migrations.AddField(
            model_name='warning',
            name='status_spending',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
