# Generated by Django 4.1.7 on 2023-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_rename_status_warning_status_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='statistic_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
